DROP TABLE IF EXISTS Trafo;
 
CREATE TABLE Trafo (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  TRAFO VARCHAR(250) NOT NULL,
  DESCRIPCION VARCHAR(250) NOT NULL
);
 
INSERT INTO Trafo (ID, TRAFO, DESCRIPCION) VALUES
  (1, 'PTR_B1_OIP_MIN', 'PTR_B1_OIP_MIN'),
  (2, 'PTR_B1_RBP_MIN', 'PTR_B1_RBP_MIN'),
  (3, 'PTR_B2_OIP_MIN', 'PTR_B2_OIP_MIN');